const SECRET_KEY_ACCESS_TOKEN = "2345566666";
const SECRET_KEY_REFRESH_TOKEN = "2345566666";

//Cloudinary credentials
const CLOUDINARY_CLOUD_NAME = "dzhkycj98";
const CLOUDINARY_API_KEY = "688856818615515";
const CLOUDINARY_API_SECRET_KEY = "0NuYTSpvvx-mZcnwfs2CtVob_kQ";

module.exports = {
  SECRET_KEY_ACCESS_TOKEN,
  SECRET_KEY_REFRESH_TOKEN,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET_KEY,
};
